name: 'Tests Setup Configu CLI Action'

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test-default:
    name: 'Test default configuration'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Configu CLI
        uses: ./

      - name: Validate Configu CLI installation
        run: configu version

  test-version:
    name: 'Test version configuration'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [0.0.105, latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Configu CLI - ${{ matrix['version'] }}
        uses: ./
        with:
          version: ${{ matrix['version'] }}

      - name: Validate Configu CLI Version - ${{ matrix['version'] }}
        if: ${{ matrix['version'] != 'latest' }}
        run: configu version | grep ${{ matrix['version'] }}

      - name: Validate Configu CLI Version - ${{ matrix['version'] }}
        if: ${{ matrix['version'] == 'latest' }}
        run: configu version | grep '@configu/cli'

  test-login-credentials:
    name: 'Test login with credentials from configuration'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Configu CLI
        uses: ./
        with:
          org: ${{ secrets.CONFIGU_ORG }}
          token: ${{ secrets.CONFIGU_TOKEN }}

      - name: Validate Configu API access
        run: configu list

  test-env-credentials:
    name: 'Test auth with credentials from environment variables'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Configu CLI
        uses: ./

      - name: Validate Configu API access
        run: configu list
        env:
          CONFIGU_ORG: ${{ secrets.CONFIGU_ORG }}
          CONFIGU_TOKEN: ${{ secrets.CONFIGU_TOKEN }}
